name: Docker Image CI

on:
  push:
    branches: [ "ros2" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check files
        run: |
          if [ ! -f ./.github/images.yml ]; then
              echo "images.yml not found"
              exit 1
          fi

      - name: Push to ghcr.io
        run: |
          while IFS= read -r line; do
          if [ ! -z "$line" ]; then
            echo "Processing image tag: $line"
            docker pull georgno/fhtw-ros:$line
            docker tag georgno/fhtw-ros:$line ghcr.io/tw-robotics/docker-ros:$line
            docker push ghcr.io/tw-robotics/docker-ros:$line
          fi
          done < ./.github/images.yml